name: Automated tests

on:
  schedule:
    - cron: '0 5 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get install google-chrome-stable
          `google-chrome version`
          google-chrome --version
          `chromedriver version` 
          chromedriver --version
        

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt


        env:
          USER_1_Email: ${{ secrets.USER_1_Email }}
          USER_1_Password: ${{ secrets.USER_1_Password }}
          USER_2_Email: ${{ secrets.USER_2_Email }}
          USER_2_Password: ${{ secrets.USER_2_Password }}
          USER_3_Email: ${{ secrets.USER_3_Email }}
          USER_3_Password: ${{ secrets.USER_3_Password }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Run tests with headless Chrome
        run: |
          source .venv/bin/activate
          pytest --headless=True
