name: Manual start tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: headless=True
        type: choice
        options:
          - headless=True
          - headless=False


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get remove google-chrome-stable
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt


        env:
          USER_1_Email: ${{ secrets.USER_1_Email }}
          USER_1_Password: ${{ secrets.USER_1_Password }}
          USER_2_Email: ${{ secrets.USER_2_Email }}
          USER_2_Password: ${{ secrets.USER_2_Password }}
          USER_3_Email: ${{ secrets.USER_3_Email }}
          USER_3_Password: ${{ secrets.USER_3_Password }}
          BASE_URL: ${{ secrets.BASE_URL }}
          URL: ${{ secrets.URL }}
          SELENOID: ${{ secrets.SELENOID }}

      - name: Run tests with headless Chrome
        if: "github.event.inputs.deployment_target == 'headless=True'"
        run: |
          source .venv/bin/activate
          pytest --headless=True

      - name: Run tests with non-headless Chrome, on Selenoid
        if: "github.event.inputs.deployment_target == 'headless=False'"
        run: |
          source .venv/bin/activate
          pytest
