name: Automated tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: headless=True
        type: choice
        options:
          - headless=True
          - headless=False


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt


        env:
          USER_1_Email: ${{ secrets.USER_1_Email }}
          USER_1_Password: ${{ secrets.USER_1_Password }}
          USER_2_Email: ${{ secrets.USER_2_Email }}
          USER_2_Password: ${{ secrets.USER_2_Password }}
          USER_3_Email: ${{ secrets.USER_3_Email }}
          USER_3_Password: ${{ secrets.USER_3_Password }}
          BASE_URL: ${{ secrets.BASE_URL }}
          URL: ${{ secrets.URL }}
          SELENOID: ${{ secrets.SELENOID }}

      - name: Run tests with headless Chrome
        if: "github.event.inputs.deployment_target == 'headless==True'"
        run: |
          source .venv/bin/activate
          touch .env
            echo "USER_1_Email=${{ secrets.USER_1_Email }}" >> .env
            echo "USER_1_Password=${{ secrets.USER_1_Password }}" >> .env
            echo "USER_2_Email=${{ secrets.USER_2_Email }}" >> .env
            echo "USER_2_Password=${{ secrets.USER_2_Password }}" >> .env
            echo "USER_3_Email=${{ secrets.USER_3_Email }}" >> .env
            echo "USER_3_Password=${{ secrets.USER_3_Password }}" >> .env
            echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
            echo "URL=${{ secrets.URL }}" >> .env
            echo "SELENOID=${{ secrets.SELENOID }}" >> .env
            cat .env
          pytest pytest --headless=True
      - name: Run tests with non-headless Chrome, on Selenoid
        if: "github.event.inputs.deployment_target == 'headless==False'"
        run: |
          source .venv/bin/activate
          touch .env
            echo "API_AUTHORIZATION=${{ secrets.API_AUTHORIZATION }}" >> .env
            echo "API_URL=${{ secrets.API_URL }}" >> .env
            echo "USERNAME=${{ secrets.USERNAME }}" >> .env
            echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
            echo "TESTOMATIO=${{ secrets.TESTOMATIO }}" >> .env
            cat .env
          pytest pytest --headless=False
